export const FETCH_CHARACTERS_DETAILS = "FETCH_CHARACTERS_DETAILS";
export const FETCH_CHARACTERS_DETAILS_SUCCCESS =
  "FETCH_CHARACTERS_DETAILS_SUCCCESS";
export const FETCH_CHARACTERS_DETAILS_ERROR = "FETCH_CHARACTERS_DETAILS_ERROR";
export const FETCH_CHARACTERS_ZERO = "FETCH_CHARACTERS_ZERO";
